//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriasRomanJonathan_Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aviones()
        {
            this.Misiones = new HashSet<Misiones>();
            this.Operaciones = new HashSet<Operaciones>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MarcaID { get; set; }
        public Nullable<int> ModeloID { get; set; }
        public Nullable<int> TecnicoID { get; set; }
        public string NumeroSerie { get; set; }
        public string NombreFantasia { get; set; }
        public Nullable<double> AnchoAlaAla { get; set; }
        public Nullable<double> Alto { get; set; }
        public Nullable<double> LargoPuntaCola { get; set; }
        public Nullable<double> DistanciaMaxima { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> CantidadInventario { get; set; }
    
        public virtual EstadoAvion EstadoAvion { get; set; }
        public virtual MarcaAvion MarcaAvion { get; set; }
        public virtual ModeloAvion ModeloAvion { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Misiones> Misiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operaciones> Operaciones { get; set; }
    }
}
