//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriasRomanJonathan_Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misiones
    {
        public int ID { get; set; }
        public string NumeroDespegue { get; set; }
        public string NombreMision { get; set; }
        public Nullable<System.DateTime> FechaDespegue { get; set; }
        public Nullable<System.DateTime> FechaAterrizaje { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string DetallesMision { get; set; }
        public Nullable<int> AvionID { get; set; }
        public Nullable<int> TecnicoID { get; set; }
        public string NombrePiloto { get; set; }
    
        public virtual Aviones Aviones { get; set; }
        public virtual EstadoMision EstadoMision { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
