//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriasRomanJonathan_Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int ID { get; set; }
        public Nullable<int> TipoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string DetallesTecnicos { get; set; }
        public Nullable<int> AvionID { get; set; }
        public Nullable<int> TecnicoID { get; set; }
    
        public virtual Aviones Aviones { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
    }
}
