//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriasRomanJonathan_Proyecto2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortavionesDBEntities : DbContext
    {
        public PortavionesDBEntities()
            : base("name=PortavionesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aviones> Aviones { get; set; }
        public virtual DbSet<EstadoAvion> EstadoAvion { get; set; }
        public virtual DbSet<EstadoMision> EstadoMision { get; set; }
        public virtual DbSet<MarcaAvion> MarcaAvion { get; set; }
        public virtual DbSet<Misiones> Misiones { get; set; }
        public virtual DbSet<ModeloAvion> ModeloAvion { get; set; }
        public virtual DbSet<Operaciones> Operaciones { get; set; }
        public virtual DbSet<Tecnicos> Tecnicos { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
    }
}
